{% set name = "pymilvus" %}
{% set version = "2.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymilvus-{{ version }}.tar.gz
  sha256: 9ef460b940782a42e1b7b8ae0da03d8cc02d9d80044d13f4b689a7c935ec7aa7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - gitpython
  run:
    - python >=3.8
    - setuptools >69
    - setuptools <70.1 # [py<=38]
    - grpcio >=1.49.1
    - protobuf >=3.20.0
    - python-dotenv >=1.0.1,<2.0.0
    - ujson >=2.0.0
    - pandas >=1.2.4
    - numpy <1.25.0; # [py<=38]
    - milvus-lite >=2.4.0 # [not win]

test:
  imports:
    - pymilvus.MilvusClient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://milvus.io
  dev_url: https://github.com/milvus-io/pymilvus
  summary: Python Sdk for Milvus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
    - cclinet
