{% set name = "pymilvus" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymilvus-{{ version }}.tar.gz
  sha256: f1d1a2e9d5172fea3e0a5d396bed9de561a2b93a4d3e1945fdf68b74d771fb05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=67
    - wheel
    - setuptools-scm >=6.2
    - gitpython
  run:
    - python >=3.7
    - setuptools >=67
    - grpcio >=1.49.1,<=1.60.0
    - grpcio-tools
    - protobuf >=3.20.0
    - environs <=9.5.0
    - ujson>=2.0.0
    - pandas >=1.2.4
    - numpy <1.25.0,
    - requests,
    - minio >=7.0.0,
    - pyarrow >=12.0.0,
    - azure-storage-blob,
    - scipy",

test:
  imports:
    - pymilvus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/milvus-io/pymilvus
  summary: Python Sdk for Milvus
  dev_url: https://github.com/milvus-io/pymilvus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cclinet
    - ndmaxar
    - oblute
    - rluria14
