{% set name = "pymilvus" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymilvus-{{ version }}.tar.gz
  sha256: 8622233c49aa9d27b84e6ee54f30d6370136a8ef4f2362b95d6499a21f5305c0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - gitpython
    - setuptools >=42
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - grpcio >=1.22.0,<1.38.0
    - grpcio-tools >=1.22.0,<1.38.0
    - requests >=2.22.0
    - ujson >=2.0.0
    # seemingly needed for compatibility
    - protobuf <3.21.0

test:
  imports:
    - milvus
    - milvus.client
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/milvus-io/pymilvus
  summary: Python Sdk for Milvus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - ndmaxar
    - oblute
    - rluria14
    - xylar
