{% set name = "pymilvus" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymilvus-{{ version }}.tar.gz
  sha256: 13923c0bdfd670d370a69031416ce28a19ed8ad53e3674903c019480b9370820

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - gitpython
  run:
    - grpcio >=1.37
    - grpcio-tools >=1.37
    - python >=3.7
    - requests >=2.22.0
    - ujson >=2.0.0,<=5.1.0
    - mmh3 >=2.0,<=3.0.0
    - pandas >=1.2.4

test:
  imports:
    - pymilvus
#   commands:
#     - pip check
#   requires:
#     - pip

about:
  home: https://github.com/milvus-io/pymilvus
  summary: Python Sdk for Milvus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - ndmaxar
    - oblute
    - rluria14
