context:
  name: pymilvus
  version: 2.5.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymilvus-${{ version }}.tar.gz
  sha256: 611732428ff669d57ded3d1f823bdeb10febf233d0251cce8498b287e5a10ce8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=67
    - wheel
    - gitpython
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}
    - setuptools >69
    - grpcio >=1.49.1,<=1.67.1
    - protobuf >=3.20.0
    - python-dotenv >=1.0.1,<2.0.0
    - ujson >=2.0.0
    - pandas >=1.2.4
    - ${{ "milvus-lite" >=2.4.0" if not win }}

tests:
  - python:
      imports:
        - milvus
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python Sdk for Milvus
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/milvus-io/pymilvus

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
