# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.6.3
  python_check_max: "3.14"

package:
  name: pymilvus
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pymilvus/pymilvus-${{ version }}.tar.gz
  sha256: 10647808f201003d24eead2890722ffcba4b1ef713eff86c8da9623f93071ed9

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - gitpython
    - pip
    - python ${{ python_min }}.*
    - setuptools >=67
    - setuptools-scm >=6.2
    - wheel
  run:
    - grpcio >=1.66.2,!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0
    - orjson >=3.10.15
    - pandas >=1.2.4
    - protobuf >=5.27.2
    - python >=${{ python_min }}
    - python-dotenv >=1.0.1,<2.0.0
    - setuptools >69

tests:
  - python:
      imports: pymilvus
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  homepage: https://github.com/milvus-io/pymilvus
  summary: Python Sdk for Milvus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - ndmaxar
    - oblute
    - rluria14
    - bollwyvl
